// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxjyznmymjpbcourgpuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4anl6bm15bWpwYmNvdXJncHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NTY5ODcsImV4cCI6MjA3NTEzMjk4N30.madT0a1ML19W9R7EngzhMvDkun1F3vR8ogsgHtKBwEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});